---
version: 2
plan:
  project-key: OP
  key: GIST
  name: Build and Deploy GIST API

# List of plan's stages and jobs
stages:
  - Test the gist service:
      jobs:
        - Test
  - Build The Native Image:
      jobs:
        - Build
  - Deploy the image:
      jobs:
        - Deploy

#Job definition
Test:
  tasks:
    - script:
        - export JAVA_HOME=/Users/eework/.sdkman/candidates/java/17.0.5-amzn
        - mvn test
    - test-parser:
        type: junit
        test-results: '**target/surefire-reports/*.xml'
  # Job's requirements
#  requirements:
#    - JDK
#    - MVN

Build:
  tasks:
    - script:
        - export JAVA_HOME=/Users/eework/.sdkman/candidates/java/17.0.5-amzn
        - mvn package -Dnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true
  # Job's artifacts. Artifacts are shared by default.
#  artifacts:
#    - name: Native Executable
#      pattern: target/gist-api-1.0-SNAPSHOT-runner
  # Job's requirements
#  requirements:
#    - Docker
#    - JDK
#    - MVN

Deploy:
  tasks:
    - script:
        docker compose up -d
